version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      # - ./media:/vol/web/media
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py loaddata books_fixture.json
             python manage.py runserver 0.0.0.0:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
  
  celery:
    restart: always
    build:
      context: .
    command: ./scripts/run_celery.sh
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - app
      - rabbitmq3
  
  beat:
    build:
        context: .
    command: ./scripts/run_celery_beat.sh
    volumes:
        - .:/app
    depends_on:
        - celery
        - rabbitmq3

  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
