# Generated by Django 4.2.8 on 2023-12-14 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["title", "author", "-inventory"]},
        ),
        migrations.AlterUniqueTogether(
            name="book",
            unique_together={("title", "author", "cover")},
        ),
    ]
