# Generated by Django 4.2.8 on 2023-12-15 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("borrowing_service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_session_id", models.CharField(max_length=255)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("DOLLAR", "usd"),
                            ("HRYVNIA", "uah"),
                            ("EURO", "eur"),
                            ("POUND_STERLING", "gbp"),
                        ],
                        default="DOLLAR",
                        max_length=25,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("PAYMENT", "payment"),
                            ("SETUP", "setup"),
                            ("SUBSCRIPTION", "subscription"),
                        ],
                        default="PAYMENT",
                        max_length=30,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("NO_PAYMENT_REQUIRED", "no_payment_required"),
                            ("PAID", "paid"),
                            ("UNPAID", "unpaid"),
                        ],
                        default="UNPAID",
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLETED", "completed"),
                            ("EXPIRED", "expired"),
                            ("OPEN", "open"),
                        ],
                        default="OPEN",
                        max_length=40,
                    ),
                ),
                (
                    "borrowing_overdue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="borrowing_service.borrowing",
                    ),
                ),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "pending"), ("PAID", "paid")],
                        default="PENDING",
                        max_length=40,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("PAYMENT", "payment"), ("FINE", "fine")],
                        default="PAYMENT",
                        max_length=40,
                    ),
                ),
                ("session_url", models.URLField()),
                (
                    "money_to_be_paid",
                    models.DecimalField(decimal_places=2, max_digits=10000),
                ),
                (
                    "borrowing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="borrowing_service.borrowing",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="payment_service.session",
                    ),
                ),
            ],
        ),
    ]
