# Generated by Django 4.2.8 on 2023-12-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="money_to_be_paid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
