# Generated by Django 4.0.4 on 2023-12-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='session_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
