# Generated by Django 4.2.8 on 2023-12-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment_service", "0002_alter_payment_session_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "pending"),
                    ("PAID", "paid"),
                    ("EXPIRED", "expired"),
                ],
                default="PENDING",
                max_length=40,
            ),
        ),
    ]
