# Generated by Django 4.0.4 on 2023-12-14 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_service', '0002_alter_book_options_alter_book_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='book_service.book')),
            ],
            options={
                'ordering': ['-borrow_date'],
            },
        ),
    ]
