# Generated by Django 4.0.4 on 2023-12-14 15:23

import borrowing_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing_service', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='expected_return_date',
            field=models.DateField(default=borrowing_service.models.set_expected_return_date),
        ),
    ]
